// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBswYeHU33yfNh4MFEyhcfPyLqMg5ZXmz8',
    appId: '1:845981097587:web:02899aefc9086df9b49406',
    messagingSenderId: '845981097587',
    projectId: 'otobix-auction-app-final',
    authDomain: 'otobix-auction-app-final.firebaseapp.com',
    storageBucket: 'otobix-auction-app-final.firebasestorage.app',
    measurementId: 'G-KBTBHYY7JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOCTtoWbgDuXaVZFyrTBXlN1_oTj8x6DE',
    appId: '1:845981097587:android:cc20217a520b5848b49406',
    messagingSenderId: '845981097587',
    projectId: 'otobix-auction-app-final',
    storageBucket: 'otobix-auction-app-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB-wjIKLovgSWFDpEoMHsgXPN3RyBr9wM',
    appId: '1:845981097587:ios:59abc40588900899b49406',
    messagingSenderId: '845981097587',
    projectId: 'otobix-auction-app-final',
    storageBucket: 'otobix-auction-app-final.firebasestorage.app',
    iosBundleId: 'com.otobix.auctionapp',
  );

}